import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saphire - Digital Assets Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        <main className="flex flex-col relative min-h-screen">
          <Provider>
            <Navbar />
            <div className="flex-grow flex-1">{children}</div>
          </Provider>
        </main>
      </body>
    </html>
  );
}
// changes 
// npm i @tanstack/react-query@4.36.1 